services:
  app:
    build:
      context: docker/app/Dockerfile
    ports:
      - "7860:7860"

  api:
    image: python:3.11.11-slim
    command: ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
      - "8000:8001"