services:
  app:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    command: ["python", "src/app.py"]
    ports:
      - "7860:7860"

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    entrypoint: ["/usr/bin/supervisord", "-c", "/app/supervisord.conf"]
    command: ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
      - "8000:8001"
