services:
  app:
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    command: ["python", "src/app.py"]
    environment:
      - API_ENDPOINT='0.0.0.0:7860'
    ports:
      - "7860:7860"

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    entrypoint: '/app/entrypoint.sh'
    command: ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
      - "8001:8001"
